### ISSUE TITLE
dodanie możliwości pobrania danych godzinowych

### ISSUE THREAD

**Issue by tmikulski** [Bozydarek/tauron_statistics#1]
Witam,
jak w temacie, jest szansa na pobranie danych godzinowych?

**Comment by Bozydarek** [comment]
Hej @tmikulski :wave: 
Aktualnie, ten program nie pobiera i nie analizuje danych godzinowych - na potrzeby tego projektu są to zbędne dane. Pobierane są dane miesięczne (Tauron przesyła jako osobne dni, które program agreguje w miesiące). Pomaga to monitorować dzienne i miesięczne zużycie, roczny balans, a także porównywać to z poprzednimi latami. 

Takeże wracając do Twojego pytania, obecnie nie planuję dopisywać takiej funkcjonalności, ale może w przyszłości ją rozważę :) Jeśli bardzo potrzebujesz danych godzinowych to na Githubie możesz znaleźć podobne projekty, które takie dane udostępniają.

**Comment by tmikulski** [comment]
@Bozydarek  dzięki za odpowiedź, ale temat i tak jest już nieaktualny. Chciałem mieć wyświetlane aktualne zużycie co godzinę, ale tauron blokuje możliwość logowania na 8h jeśli logowań jest zbyt dużo. Miałem ustawione logowanie co 4h i już to było zbyt częste.
